CREATE TABLE users (id text PRIMARY KEY, email text UNIQUE NOT NULL, name text NOT NULL, role text NOT NULL CHECK (role IN ('teacher', 'student')), password_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE classes (id text PRIMARY KEY, teacher_id text NOT NULL REFERENCES users(id), name text NOT NULL, period text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE memberships (class_id text REFERENCES classes(id), student_id text REFERENCES users(id), PRIMARY KEY (class_id, student_id));
CREATE TABLE competency_nodes (id text PRIMARY KEY, title text NOT NULL, prerequisites jsonb NOT NULL DEFAULT '[]');
CREATE TABLE student_profiles (student_id text REFERENCES users(id), competency_id text REFERENCES competency_nodes(id), alpha numeric NOT NULL, beta numeric NOT NULL, flags jsonb NOT NULL DEFAULT '[]', evidence jsonb NOT NULL DEFAULT '[]', updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (student_id, competency_id));
CREATE TABLE assignments (id text PRIMARY KEY, class_id text NOT NULL REFERENCES classes(id), teacher_id text NOT NULL REFERENCES users(id), domain text NOT NULL, title text NOT NULL, payload jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE sessions (id text PRIMARY KEY, assignment_id text REFERENCES assignments(id), class_id text REFERENCES classes(id), student_id text REFERENCES users(id), state text NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE generated_items (id text PRIMARY KEY, session_id text NOT NULL REFERENCES sessions(id), prompt_version text NOT NULL, model_metadata jsonb NOT NULL, verifier_result jsonb NOT NULL, item jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE trace_snapshots (id bigserial PRIMARY KEY, session_id text REFERENCES sessions(id), atlas_snapshot text NOT NULL, trace_features jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE idempotency_keys (session_id text REFERENCES sessions(id), key text NOT NULL, response jsonb NOT NULL, PRIMARY KEY (session_id, key));
CREATE TABLE auth_sessions (id text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id), expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX classes_teacher_idx ON classes(teacher_id);
CREATE INDEX assignments_class_idx ON assignments(class_id);
CREATE INDEX sessions_class_idx ON sessions(class_id);
CREATE INDEX sessions_student_idx ON sessions(student_id);
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY teacher_class_sessions ON sessions FOR SELECT USING (class_id IN (SELECT id FROM classes WHERE teacher_id = current_setting('app.user_id', true)));
ALTER TABLE student_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY teacher_class_profiles ON student_profiles FOR SELECT USING (student_id IN (SELECT student_id FROM memberships m JOIN classes c ON c.id = m.class_id WHERE c.teacher_id = current_setting('app.user_id', true)));
