"use strict";

const { pgTable, text, timestamp, jsonb, numeric, primaryKey, bigserial, bigint, index } = require("drizzle-orm/pg-core");

const users = pgTable("users", { id: text("id").primaryKey(), email: text("email").notNull().unique(), name: text("name").notNull(), role: text("role").notNull(), passwordHash: text("password_hash").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
const classes = pgTable("classes", { id: text("id").primaryKey(), teacherId: text("teacher_id").notNull().references(() => users.id), name: text("name").notNull(), period: text("period"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("classes_teacher_idx").on(table.teacherId)]);
const memberships = pgTable("memberships", { classId: text("class_id").notNull().references(() => classes.id), studentId: text("student_id").notNull().references(() => users.id) }, (table) => [primaryKey({ columns: [table.classId, table.studentId] })]);
const competencyNodes = pgTable("competency_nodes", { id: text("id").primaryKey(), title: text("title").notNull(), prerequisites: jsonb("prerequisites").notNull().default([]) });
const studentProfiles = pgTable("student_profiles", { studentId: text("student_id").notNull().references(() => users.id), competencyId: text("competency_id").notNull().references(() => competencyNodes.id), alpha: numeric("alpha").notNull(), beta: numeric("beta").notNull(), flags: jsonb("flags").notNull().default([]), evidence: jsonb("evidence").notNull().default([]), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [primaryKey({ columns: [table.studentId, table.competencyId] })]);
const assignments = pgTable("assignments", { id: text("id").primaryKey(), classId: text("class_id").notNull().references(() => classes.id), teacherId: text("teacher_id").notNull().references(() => users.id), domain: text("domain").notNull(), title: text("title").notNull(), payload: jsonb("payload").notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("assignments_class_idx").on(table.classId)]);
const diagnosticSessions = pgTable("sessions", { id: text("id").primaryKey(), assignmentId: text("assignment_id").references(() => assignments.id), classId: text("class_id").notNull().references(() => classes.id), studentId: text("student_id").notNull().references(() => users.id), state: text("state").notNull(), payload: jsonb("payload").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("sessions_class_idx").on(table.classId), index("sessions_student_idx").on(table.studentId)]);
const generatedItems = pgTable("generated_items", { id: text("id").primaryKey(), sessionId: text("session_id").notNull().references(() => diagnosticSessions.id), promptVersion: text("prompt_version").notNull(), modelMetadata: jsonb("model_metadata").notNull(), verifierResult: jsonb("verifier_result").notNull(), item: jsonb("item").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
const traceSnapshots = pgTable("trace_snapshots", { id: bigserial("id", { mode: "number" }).primaryKey(), sessionId: text("session_id").notNull().references(() => diagnosticSessions.id), atlasSnapshot: text("atlas_snapshot").notNull(), traceFeatures: jsonb("trace_features").notNull(), explanation: text("explanation"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
const idempotencyKeys = pgTable("idempotency_keys", { sessionId: text("session_id").notNull().references(() => diagnosticSessions.id), key: text("key").notNull(), response: jsonb("response").notNull() }, (table) => [primaryKey({ columns: [table.sessionId, table.key] })]);
const authSessions = pgTable("auth_sessions", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("auth_sessions_user_idx").on(table.userId)]);
const ontologyRevisions = pgTable("ontology_revisions", { id: text("id").primaryKey(), domain: text("domain").notNull(), version: text("version").notNull(), title: text("title").notNull(), status: text("status").notNull(), publishedAt: timestamp("published_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
const ontologyConcepts = pgTable("ontology_concepts", { revisionId: text("revision_id").notNull().references(() => ontologyRevisions.id), id: text("id").notNull(), title: text("title").notNull(), domain: text("domain").notNull(), topic: text("topic").notNull(), track: text("track").notNull().default("legacy"), abstraction: text("abstraction"), definition: text("definition"), level: text("level").notNull(), diagnosticMetadata: jsonb("diagnostic_metadata").notNull().default({}) }, (table) => [primaryKey({ columns: [table.revisionId, table.id] }), index("ontology_concepts_revision_domain_idx").on(table.revisionId, table.domain), index("ontology_concepts_revision_track_idx").on(table.revisionId, table.track)]);
const ontologyRelations = pgTable("ontology_relations", { revisionId: text("revision_id").notNull().references(() => ontologyRevisions.id), sourceConceptId: text("source_concept_id").notNull(), targetConceptId: text("target_concept_id").notNull(), relationType: text("relation_type").notNull() }, (table) => [primaryKey({ columns: [table.revisionId, table.sourceConceptId, table.targetConceptId, table.relationType] }), index("ontology_relations_target_idx").on(table.revisionId, table.targetConceptId)]);
const studentOntologyBeliefs = pgTable("student_ontology_beliefs", { studentId: text("student_id").notNull().references(() => users.id), ontologyRevisionId: text("ontology_revision_id").notNull().references(() => ontologyRevisions.id), competencyId: text("competency_id").notNull(), alpha: numeric("alpha").notNull(), beta: numeric("beta").notNull(), flags: jsonb("flags").notNull().default([]), evidence: jsonb("evidence").notNull().default([]), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [primaryKey({ columns: [table.studentId, table.ontologyRevisionId, table.competencyId] }), index("student_ontology_beliefs_revision_student_idx").on(table.ontologyRevisionId, table.studentId), index("student_ontology_beliefs_student_idx").on(table.studentId)]);
const evidenceEvaluations = pgTable("evidence_evaluations", { id: text("id").primaryKey(), sessionId: text("session_id").notNull().references(() => diagnosticSessions.id), traceSnapshotId: bigint("trace_snapshot_id", { mode: "number" }).notNull().references(() => traceSnapshots.id), ontologyRevisionId: text("ontology_revision_id").notNull().references(() => ontologyRevisions.id), competencyId: text("competency_id").notNull(), evaluatorPromptVersion: text("evaluator_prompt_version").notNull(), modelMetadata: jsonb("model_metadata").notNull(), criterionResults: jsonb("criterion_results").notNull(), aggregate: jsonb("aggregate").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("evidence_evaluations_session_idx").on(table.sessionId, table.createdAt), index("evidence_evaluations_snapshot_idx").on(table.traceSnapshotId)]);
const competencyBeliefUpdates = pgTable("competency_belief_updates", { id: text("id").primaryKey(), studentId: text("student_id").notNull().references(() => users.id), ontologyRevisionId: text("ontology_revision_id").notNull().references(() => ontologyRevisions.id), competencyId: text("competency_id").notNull(), sessionId: text("session_id").notNull().references(() => diagnosticSessions.id), evidenceEvaluationId: text("evidence_evaluation_id").notNull().references(() => evidenceEvaluations.id), prior: jsonb("prior").notNull(), next: jsonb("next").notNull(), decision: jsonb("decision").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("competency_belief_updates_node_idx").on(table.studentId, table.ontologyRevisionId, table.competencyId, table.createdAt)]);

module.exports = { users, classes, memberships, competencyNodes, studentProfiles, assignments, diagnosticSessions, generatedItems, traceSnapshots, idempotencyKeys, authSessions, ontologyRevisions, ontologyConcepts, ontologyRelations, studentOntologyBeliefs, evidenceEvaluations, competencyBeliefUpdates };
